version: '2.1'
services:
    postgres:
        image: postgres:latest
        expose:
          - "5432"
        volumes:
            - ./conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    nikonikoapi:
        build:
            context: .
            args:
                dbhost: ${DB_HOST:-postgres}
                dbuser: ${DB_USERNAME:-nikoniko}
        environment:
            - DO_BOOTSTRAP_DB=${DO_BOOTSTRAP_DB:-0}
            - JWT_SECRET_KEY
            - LOGLEVEL
        links:
            - postgres
    nginx:
        image: nginx:latest
        volumes:
            - ./conf/etc/nginx/nikonikoapi-dev.conf:/etc/nginx/conf.d/nikonikoapi-dev.conf
            - ./conf/etc/nginx/nikonikoapi.conf:/etc/nginx/conf.d/nikonikoapi.conf
            - ./conf/etc/nginx/localhost.key:/etc/nginx/localhost.key
            - ./conf/etc/nginx/localhost.crt:/etc/nginx/localhost.crt
            - ./conf/etc/nginx/uwsgi_params:/etc/nginx/uwsgi_params
              # to generate, `openssl dhparam -out dhparams.pem 2048`
            - ./conf/etc/nginx/dhparams.pem:/etc/nginx/dhparams.pem
        expose:
            - "443"
          # - "8080"
        ports:
            - "0.0.0.0:8443:443"
          # - "0.0.0.0:8080:8080"
        links:
            - nikonikoapi
