version: '2.0'
services:
    postgres:
        image: postgres:latest
        expose:
          - "5432"
        volumes:
            - ./conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    nikonikoapi:
        build:
            context: .
            args:
                dbhost: postgres
                dbuser: nikoniko
        depends_on:
            postgres:
                condition: service_started
        expose:
            - "8080"
        ports:
            - "8080:8080"
        links:
            - postgres
