#%RAML 1.0

title: Nikoniko API
baseUri: http://nikoniko.yokiyoki.com/api/{version}
version: v1

schemas:
  credentials: !include schemas/credentials-schema.json
  feeling: !include schemas/feeling-schema.json
  person: !include schemas/person-schema.json
  board: !include schemas/board-schema.json

resourceTypes:
  collection:
      description: Collection of all the <<resourcePathName>> in Nikoniko.
      get:
        description: Retrieve all or some <<resourcePathName>> data.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
  collection-item:
      description: Entity representing a <<resourcePathName|!singularize>>
      get:
        description: |
          Get the <<resourcePathName|!singularize>>
          With <<resourcePathName|!singularize>>Id =
          {<<resourcePathName|!singularize>>Id}
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleItem>>
          404:
            body:
              application/json:
                example: |
                  { "message": "<<resourcePathName|!singularize>> not found" }

/login:
  post:
    description: Login endpoint
    body:
      application/json:
        schema: credentials
        example: !include examples/credentials-example.json
    responses:
      200:
        headers:
          Authorization:
            description: Access Token
            example: 5757gh76...
            required: true
      401:
/users/{userId}:
  get:
    description: |
      Get the User
      With userId={userId}
/people:
  type:
    collection:
      exampleCollection: !include examples/people-example.json
  get:
    queryParameters:
      inBoard:
        type: integer
        required: false
  /{personId}:
    type:
      collection-item:
        exampleItem: !include examples/person-example.json

/boards:
  type:
    collection:
      exampleCollection: !include examples/boards-example.json
  /{boardId}:
    type:
      collection-item:
        exampleItem: !include examples/board-example.json
    get:
      queryParameters:
        fromDate:
          type: string
          required: true
        toDate:
          type: string
          required: true

/reportedFeelings/boards/{boardId}/people/{personId}/dates/{date}:
  post:
    description: Insert or update a reportedFeeling
    body:
      application/json:
        schema: feeling
        example: !include examples/reportedfeeling-example.json
  get:
    description: |
      Get the reportedFeeling
      With boardId = boardId, personId = personId and date = date
    responses:
      200:
        body:
          application/json:
            example: !include examples/reportedfeeling-example.json
      404:
        body:
          application/json:
            example: |
              { "message": "reportedFeeling not found" }
