#!/usr/bin/env sh
### BEGIN INIT INFO
# Provides:          nikonikoapi
# Required-Start:    $remote_fs $time
# Required-Stop:     umountnfs $time
# X-Stop-After:      sendsigs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: nikoniko boards API
# Description:
#
#
### END INIT INFO

CONF=/etc/default/nikonikoapi
INI=/etc/uwsgi.ini

[ -r "${CONF}" ] && . ${CONF}

exec uwsgi --ini ${INI} --daemonize /var/log/uwsgi.log --logfile-chown --force-cwd /
